### ISSUE TITLE
Add search feature to let users search the content and history.

### ISSUE THREAD

**Issue by hamidra** [Premiurly/polkassembly#39]
It would be nice to add search capability to let the users search the history and content of the discussions in the website for specific keywords or queries.
e.g. someone might know that there is specific treasury or motion proposal but they might not have the direct link or the proposal  number, they should be to search the topic or keyword to find that discussion.

Currently the workaround is to search using google and scope the search to polkassembly site, but would be nice if the polkassembly  provide such feature.

**Comment by alphainfinitus** [comment]
We are pleased to announce that the issue regarding the improvement of searching for posts and discussions on Polkassembly has been successfully addressed and closed with https://github.com/polkassembly/polkassembly/pull/333.

The following improvements that have been implemented:

- Enhanced search algorithm: We have upgraded the search functionality to ensure more accurate and relevant results. The new algorithm takes into account exact title matches, allowing users to find posts and discussions more efficiently.

- Customized search options: We have implemented additional search filters that enable users to narrow down their searches. These options include searching within discussions only, filtering by specific categories, and more.

- Real-time indexing: To eliminate the delays caused by Google indexing, we have implemented a real-time indexing system. This ensures that new entries are promptly available for search, improving the overall user experience.

We appreciate your patience and valuable feedback during the resolution of this issue. Your suggestions and insights have been instrumental in driving these improvements.

Thank you for your continued support and contribution to the Polkassembly ecosystem.
